# syntax=docker/dockerfile:1
# check=error=true

# This Dockerfile is designed for development
ARG RUBY_VERSION=3.3.5
FROM docker.io/library/ruby:$RUBY_VERSION-slim

# Rails app lives here
WORKDIR /rails

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips postgresql-client \
    build-essential git pkg-config libpq-dev && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Add Node.js repository and install Node.js
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get update -qq && \
    apt-get install --no-install-recommends -y nodejs && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set development environment
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle"

# Create directory for assets
RUN mkdir -p /rails/app/assets/builds

# Copy entrypoint script and set permissions
COPY ./bin/docker-entrypoint-dev /usr/bin/
# RUN chmod +x /usr/bin/docker-entrypoint-dev


EXPOSE 3000
ENTRYPOINT ["docker-entrypoint-dev"]
CMD ["rails", "server", "-b", "0.0.0.0"]